# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/nucleo/gpio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goldo import pb2_options_pb2 as goldo_dot_pb2__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/nucleo/gpio.proto',
  package='goldo.nucleo.gpio',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17goldo/nucleo/gpio.proto\x12\x11goldo.nucleo.gpio\x1a\x17goldo/pb2_options.proto\"W\n\nCmdGpioSet\x12\x1d\n\x0fsequence_number\x18\x01 \x01(\x05\x42\x04\x80\xb5\x18\x05\x12\x15\n\x07gpio_id\x18\x02 \x01(\x05\x42\x04\x80\xb5\x18\x03\x12\x13\n\x05value\x18\x03 \x01(\x08\x42\x04\x80\xb5\x18\x03\x62\x06proto3')
  ,
  dependencies=[goldo_dot_pb2__options__pb2.DESCRIPTOR,])




_CMDGPIOSET = _descriptor.Descriptor(
  name='CmdGpioSet',
  full_name='goldo.nucleo.gpio.CmdGpioSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='goldo.nucleo.gpio.CmdGpioSet.sequence_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\200\265\030\005'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gpio_id', full_name='goldo.nucleo.gpio.CmdGpioSet.gpio_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\200\265\030\003'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='goldo.nucleo.gpio.CmdGpioSet.value', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\200\265\030\003'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['CmdGpioSet'] = _CMDGPIOSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CmdGpioSet = _reflection.GeneratedProtocolMessageType('CmdGpioSet', (_message.Message,), dict(
  DESCRIPTOR = _CMDGPIOSET,
  __module__ = 'goldo.nucleo.gpio_pb2'
  # @@protoc_insertion_point(class_scope:goldo.nucleo.gpio.CmdGpioSet)
  ))
_sym_db.RegisterMessage(CmdGpioSet)


_CMDGPIOSET.fields_by_name['sequence_number']._options = None
_CMDGPIOSET.fields_by_name['gpio_id']._options = None
_CMDGPIOSET.fields_by_name['value']._options = None
# @@protoc_insertion_point(module_scope)
